---
- name: launchin complete apache website
  hosts: all
  become: true
  tasks:
          - name: installing apache2
            apt:
                    name: apache2
                    state: present
